class Bits:
    FULL_BITS = 0xffff
    NOTHING_BITS = 0x0000
    GROUND_BITS = 0x0004
    BACKGROUND_OBJECT_BITS = 0x0008
    PERSONAGE_BITS = 0x0016
    PARTS_BITS = 0X0032

    NOTHING_MASK = 0x0000
    FULL_MASK = 0xffff
    GROUND_MASK = FULL_MASK
    BACKGROUND_OBJECT_MASK = FULL_MASK ^ PERSONAGE_BITS
    PERSONAGE_MASK = FULL_MASK ^ BACKGROUND_OBJECT_BITS
    PARTS_MASK = FULL_MASK ^ PARTS_BITS ^ BACKGROUND_OBJECT_BITS


