class Bits:
    FULL_BITS = 0xffff
    NOTHING_BITS = 0x0000
    GROUND_BITS = 0x0001
    BACKGROUND_OBJECT_BITS = 0x0002
    PERSONAGE_BITS = 0x0004
    PARTS_BITS = 0X0008

    NOTHING_MASK = 0x0000
    FULL_MASK = 0xffff
    GROUND_MASK = FULL_MASK
    BACKGROUND_OBJECT_MASK = FULL_MASK ^ PERSONAGE_BITS
    PERSONAGE_MASK = FULL_MASK ^ BACKGROUND_OBJECT_BITS
    PARTS_MASK = FULL_MASK ^ PARTS_BITS ^ BACKGROUND_OBJECT_BITS ^ PERSONAGE_BITS


